apiVersion: iot.enmasse.io/v1alpha1
kind: IoTConfig
metadata:
  name: default
spec:
  interServiceCertificates:
    secretCertificatesStrategy:
      caSecretName: iot-service-ca
      serviceSecretNames:
        iot-auth-service: iot-auth-service-tls
        iot-device-registry: iot-device-registry-tls
        iot-tenant-service: iot-tenant-service-tls
  services:
    deviceRegistry:
      infinispan:
        server:
          external:
            host: infinispan
            port: 11222
            username: app
            password: test12
            saslServerName: hotrod
            saslRealm: ApplicationRealm
  adapters:
    http:
      endpoint:
        secretNameStrategy:
          secretName: iot-http-adapter-tls
    mqtt:
      endpoint:
        secretNameStrategy:
          secretName: iot-mqtt-adapter-tls
    sigfox:
      endpoint:
        secretNameStrategy:
          secretName: iot-sigfox-adapter-tls
    lorawan:
      endpoint:
        secretNameStrategy:
          secretName: iot-lorawan-adapter-tls