apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: enmasse
  name: enmasse.io:iot-device-registry
rules:
  - apiGroups: [ "authentication.k8s.io" ]
    resources: [ "tokenreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources: [ "subjectaccessreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "iot.enmasse.io" ]
    resources: [ "iotprojects" ]
    verbs: [ "get", "list", "watch" ]
