apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "enmasse.io:iot-device-registry-amq-online-infra"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enmasse.io:iot-device-registry
subjects:
- kind: ServiceAccount
  name: iot-device-registry
  namespace: amq-online-infra
