apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: infinispan
  name: iot.enmasse.io:infinispan
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
